#!/bin/bash

brew install \
  autoconf \
  automake \
  ca-certificates \
  cargo-c \
  clang-format \
  cmake \
  curl \
  dos2unix \
  git \
  gsl \
  hdf5 \
  htslib \
  llvm \
  openssl \
  pipx \
  xz \
  zlib \
  zstd

if ! grep -q 'vigeas' ~/.[bz]shrc; then
    echo "export PATH=$HOME/vigeas/scripts:$PATH" >> ~/.[bz]shrc
	echo "alias vigeas="/opt/homebrew/bin/bash $HOME/scripts/vigeas"" >> ~/.[bz]shrc
fi

if command -v micromamba &> /dev/null; then
    eval "$(micromamba shell hook --shell zsh)"
    ENV_MANAGER=micromamba
elif command -v mamba &> /dev/null; then
    ENV_MANAGER=mamba
elif command -v conda &> /dev/null; then
    ENV_MANAGER=conda
else
    brew install micromamba
    eval "$(micromamba shell hook --shell zsh)"
    micromamba shell init --shell zsh --root-prefix=~/.local/share/mamba
    echo 'alias mm="micromamba"' >> ~/.zshrc
    ENV_MANAGER=micromamba
fi

if ! "$ENV_MANAGER" env list | grep -q vigeas-ill; then
    "$ENV_MANAGER" create -y -n vigeas-ill --platform osx-64 -c conda-forge -c bioconda \
      blast \
      bwa-mem2 \
      entrez-direct \
      exonerate \
      fastp \
      ghostscript \
      ivar \
      minimap2 \
      r-base \
      r-cowplot \
      r-dplyr \
      r-ggplot2 \
      r-patchwork \
      r-plyr \
      r-readr \
      r-svglite \
      samtools \
      seqkit \
      seqtk \
      spades
fi
if ! "$ENV_MANAGER" env list | grep -q vigeas-ont; then
    "$ENV_MANAGER" create -y -n vigeas-ont --platform osx-64 -c conda-forge -c bioconda \
      bbmap \
      bcftools \
      clair3 \
      exonerate \
      ghostscript \
      ivar \
      minimap2 \
      muscle \
      r-base \
      r-cowplot \
      r-dplyr \
      r-ggplot2 \
      r-patchwork \
      r-plyr \
      r-readr \
      r-svglite \
      samtools \
      seqkit \
      seqtk \
      tensorflow
    "$ENV_MANAGER" activate vigeas-ont
echo "environments:" && "$ENV_MANAGER" env list | grep vigeas

if [ ! -d "rerio" ]; then
    git clone https://github.com/nanoporetech/rerio.git
    cd rerio || exit
    python3 download_model.py --clair3
    python3 download_model.py --dorado
    ln -s "$HOME/micromamba/envs/vigeas-ont/bin/models/"* "$HOME/rerio/clair3_models/"
else
    cd
    rm -rf ~/rerio
    git clone https://github.com/nanoporetech/rerio.git
    cd rerio || exit
    python3 download_model.py --clair3
    python3 download_model.py --dorado
    ln -s "$HOME/micromamba/envs/vigeas-ont/bin/models/"* "$HOME/rerio/clair3_models/"
fi
echo "export PATH=$HOME/.local/bin:$PATH" >> ~/.[bz]shrc