#!/bin/bash

usage () {
    echo "
vigeas-illumina
--------
Viral genome assembly pipeline for WGS using <Illumina>

List available primer scheme in this workflow:
    $(basename $0) -l

Assembly + summary stats:
    $(basename $0) -w 1 -i <input path> -s <sample sheet> -d <depth> -t <threads>

Assembly:
    $(basename $0) -w 2 -i <input path> -s <sample sheet> -d <depth> -t <threads>

Summary stats:
    $(basename $0) -w 3 -i <input path> -s <sample sheet> -t <threads>

Command line parameters:
    -d arg    Minimum depth to variant calling (default: 10).
    -h        Print this help and exit.
    -i arg    Path containing the Illumina fastQ sequencing data.
    -s arg    Illumina samplesheet containing the primer scheme in the description column (i.e. ARTIC_V4-1).
    -t arg    Max number of threads (default: all cores minus 2).
    -u        Update conda dependencies.
    -v        Display version information and check for update.
    -w arg    Set the workflow option (1- assembly+summary; 2- assembly; 3- summary)."
exit -1
}

primer_scheme_list () {
    echo "
vigeas-illumina

--> Available primer schemes
----> updated: 17 Jul 2022

------------------------------------------------------------------------------------------------
target                       primer_scheme       url_reference
------------------------------------------------------------------------------------------------
CHIKV Asian/ECSA [~400pb]    ChikAsianECSA_V1    https://github.com/zibraproject/zika-pipeline
DENV-1 [~900pb]              DENV1_V1            https://doi.org/10.1038/s41467-021-22607-0
DENV-2 [~900pb]              DENV2_V1            https://doi.org/10.1038/s41467-021-22607-0
DENV-3 [~900pb]              DENV3_V1            https://doi.org/10.1038/s41467-021-22607-0
DENV-4 [~700pb]              DENV4_V1            https://doi.org/10.1038/s41467-021-22607-0
EV [~1000pb]                 ZaireEbola_V1       https://github.com/artic-network/artic-ncov2019
EV [~500pb]                  ZaireEbola_V2       https://github.com/artic-network/artic-ncov2019
EV [~400pb]                  ZaireEbola_V3       https://github.com/artic-network/artic-ncov2019
LASV L-segment [~400pb]      LassaL_V1           https://github.com/zibraproject/zika-pipeline
LASV S-segment [~400pb]      LassaS_V1           https://github.com/zibraproject/zika-pipeline
NiV  [~400pb]                Nipah_V1            https://github.com/artic-network/artic-ncov2019
OROV L-segment [~400pb]      OROV400L            https://github.com/zibraproject/zika-pipeline
OROV M-segment [~400pb]      OROV400M            https://github.com/zibraproject/zika-pipeline
OROV S-segment [~400pb]      OROV400S            https://github.com/zibraproject/zika-pipeline
SARS-CoV-2 [~400pb]          ARTIC_V1            https://github.com/artic-network/artic-ncov2019
SARS-CoV-2 [~400pb]          ARTIC_V2            https://github.com/artic-network/artic-ncov2019
SARS-CoV-2 [~400pb]          ARTIC_V3            https://github.com/artic-network/artic-ncov2019
SARS-CoV-2 [~400pb]          ARTIC_V4            https://github.com/artic-network/artic-ncov2019
SARS-CoV-2 [~400pb]          ARTIC_V4_1          https://github.com/artic-network/artic-ncov2019
SARS-CoV-2 [~1200pb]         MIDNIGHT_V1         https://doi.org/10.1093/biomethods/bpaa014
SARS-CoV-2 [~1200pb]         MIDNIGHT_V2         https://doi.org/10.1093/biomethods/bpaa014
SARS-CoV-2 [~2000pb]         FIOCRUZ-IOC_V1      https://doi.org/10.1101/2020.04.30.069039
SARS-CoV-2 [~2000pb]         FIOCRUZ-IOC_V2      https://doi.org/10.1101/2020.04.30.069039
YFV [~500pb]                 YFV500              https://github.com/zibraproject/zika-pipeline
YFV [~1000pb]                YFV1000             https://github.com/zibraproject/zika-pipeline
ZIKV Asian [~300pb]          ZikaAsian_V1        https://github.com/zibraproject/zika-pipeline
------------------------------------------------------------------------------------------------"
exit -1
}

update () {
    mamba update -y -n base -c conda-forge -c anaconda -c bioconda -c defaults conda
    mamba update -y -n vir_assembly -c conda-forge -c anaconda -c bioconda -c defaults --all
    mamba update -y -n vir_summary -c conda-forge -c anaconda -c bioconda -c defaults --all
exit -1
}

version () {
    echo "
vigeas-illumina

--> updated: 21 Ago 2022
----> Laise de Moraes [https://lpmor22.github.io/]
------> Khouri Lab, Gonçalo Moniz Institute, FIOCRUZ, Brazil"
exit -1
}

while getopts "d:hi:ls:t:uvw:" OPT; do
    case "$OPT" in
        d) DEPTH="$OPTARG";;
        h) usage;;
        i) INPUT="$OPTARG";;
        l) primer_scheme_list;;
        s) SAMPLE_SHEET="$OPTARG";;
        t) THREADS="$OPTARG";;
        u) update;;
        v) version;;
        w) WORKFLOW="$OPTARG";;
    esac
done

if [[ ! -z "$WORKFLOW" ]]; then
    if [[ "$WORKFLOW" == "1" ]]; then
        if [[ -z "$INPUT" ]] || [[ -z "$SAMPLE_SHEET" ]] || [[ -z "$DEPTH" ]]; then
            usage
        else
            LIBRARY_NAME="$(cat "$SAMPLE_SHEET" | grep "Experiment Name" | awk -F, '{print $2}')"
            ANALYSIS_DIR=$HOME/vigeas/"$LIBRARY_NAME"_ANALYSIS
            [[ ! -d "$ANALYSIS_DIR" ]] && mkdir "$ANALYSIS_DIR" && chmod 700 -R "$ANALYSIS_DIR"
            echo "" && echo "Output path: "$ANALYSIS_DIR""
            echo "" && echo "Log Analysis: "$ANALYSIS_DIR"/"$LIBRARY_NAME".log.$(uname -n).$(date +'%Y-%m-%d').txt"
            echo "" && echo "To display the log output in fulscreen: watch tail -n 20 "$ANALYSIS_DIR"/"$LIBRARY_NAME".log.$(uname -n).$(date +'%Y-%m-%d').txt"
        fi
    elif [[ "$WORKFLOW" == "2" ]]; then
        if [[ -z "$INPUT" ]] || [[ -z "$SAMPLE_SHEET" ]] || [[ -z "$DEPTH" ]]; then
            usage
        else
            LIBRARY_NAME="$(cat "$SAMPLE_SHEET" | grep "Experiment Name" | awk -F, '{print $2}')"
            ANALYSIS_DIR=$HOME/vigeas/"$LIBRARY_NAME"_ANALYSIS
            [[ ! -d "$ANALYSIS_DIR" ]] && mkdir "$ANALYSIS_DIR" && chmod 700 -R "$ANALYSIS_DIR"
            echo "" && echo "Output path: "$ANALYSIS_DIR""
            echo "" && echo "Log Analysis: "$ANALYSIS_DIR"/"$LIBRARY_NAME".log.$(uname -n).$(date +'%Y-%m-%d').txt"
            echo "" && echo "To display the log output in fulscreen: watch tail -n 20 "$ANALYSIS_DIR"/"$LIBRARY_NAME".log.$(uname -n).$(date +'%Y-%m-%d').txt"
        fi
    elif [[ "$WORKFLOW" == "3" ]]; then
        if [[ -z "$INPUT" ]] || [[ -z "$SAMPLE_SHEET" ]]; then
            usage
        else
            LIBRARY_NAME="$(cat "$SAMPLE_SHEET" | grep "Experiment Name" | awk -F, '{print $2}')"
            ANALYSIS_DIR=$HOME/vigeas/"$LIBRARY_NAME"_ANALYSIS
            [[ ! -d "$ANALYSIS_DIR" ]] && mkdir "$ANALYSIS_DIR" && chmod 700 -R "$ANALYSIS_DIR"
            echo "" && echo "Output path: "$ANALYSIS_DIR""
            echo "" && echo "Log Analysis: "$ANALYSIS_DIR"/"$LIBRARY_NAME".log.$(uname -n).$(date +'%Y-%m-%d').txt"
            echo "" && echo "To display the log output in fulscreen: watch tail -n 20 "$ANALYSIS_DIR"/"$LIBRARY_NAME".log.$(uname -n).$(date +'%Y-%m-%d').txt"
        fi
    else
        usage
    fi
else
    usage
fi

bg() {
    start_all=$(date +%s.%N)
    if [[ -z "$THREADS" ]]; then
        THREADS=$(lscpu | grep 'CPU(s):' | awk '{print $2}' | sed -n '1p' | awk '{print $1-2}')
    fi
    if [[ -z "$DEPTH" ]]; then
        DEPTH=10
    fi
    if [[ ! -z "$WORKFLOW" ]]; then
        if [[ "$WORKFLOW" == "1" ]]; then
            if [[ -z "$INPUT" ]] || [[ -z "$SAMPLE_SHEET" ]] || [[ -z "$DEPTH" ]]; then
                usage
            else
                for i in $(cat "$SAMPLE_SHEET" | sed -e '1,18d' | awk -F, '{print $1}' | sort); do
                    if [[ $(find "$INPUT" -type f -name '*_L00*') ]]; then
                        cp -v "$INPUT"/"$i"*_R1_001.fastq.gz "$ANALYSIS_DIR"/"$i".R1.fastq.gz
                        cp -v "$INPUT"/"$i"*_R2_001.fastq.gz "$ANALYSIS_DIR"/"$i".R2.fastq.gz
                    elif [[ $(find "$INPUT" -type f -name '*_1.fastq.gz') ]]; then
                        cp -v "$INPUT"/"$i"_1.fastq.gz "$ANALYSIS_DIR"/"$i".R1.fastq.gz
                        cp -v "$INPUT"/"$i"_2.fastq.gz "$ANALYSIS_DIR"/"$i".R2.fastq.gz
                    elif [[ $(find "$INPUT" -type f -name '*.R[1-2].fastq.gz') ]]; then
                        cp -v "$INPUT"/"$i".R1.fastq.gz "$ANALYSIS_DIR"/"$i".R1.fastq.gz
                        cp -v "$INPUT"/"$i".R2.fastq.gz "$ANALYSIS_DIR"/"$i".R2.fastq.gz
                    fi
                done
                source activate vigeas_illumina
                for i in $(cat "$SAMPLE_SHEET" | sed -e '1,18d' | awk -F, '{print $NF}' | sed -e 's/ChikAsianECSA.*/KP164568.1/g' -e 's/DENV1.*/NC_001477.1/g' -e 's/DENV2.*/NC_001474.2/g' -e 's/DENV3.*/NC_001475.2/g' -e 's/DENV4.*/NC_002640.1/g' -e 's/ZaireEbola.*/KR063671.1/g' -e 's/Lassa.*/NC_004296.1/g' -e 's/Nipah.*/AJ564622.1/g' -e 's/OROV400L/KP691612.1/g' -e 's/OROV400M/KP691622.1/g' -e 's/OROV400S/KP691623.1/g' -e 's/ARTIC.*/MN908947.3/g' -e 's/FIOCRUZ-IOC.*/MN908947.3/g' -e 's/MIDNIGHT.*/MN908947.3/g' -e 's/YFV.*/JF912190.1/g' -e 's/ZikaAsian.*/KJ776791.2/g' | sort -u); do
                    bwa index $HOME/vigeas/illumina/refseqs_fasta/"$i".fasta
                done
                for i in $(cat "$SAMPLE_SHEET" | sed -e '1,18d' | awk -F, '{print $1","$NF}' | sort); do
                    SAMPLE_ID=$(echo "$i" | tr -dc '[:print:]\n' | awk -F, '{print $1}')
                    PRIMER_SCHEME=$(echo "$i" | tr -dc '[:print:]\n' | awk -F, '{print $2}')
                    REF_SEQ=$(echo "$PRIMER_SCHEME" | sed -e 's/ChikAsianECSA.*/KP164568.1/g' -e 's/DENV1.*/NC_001477.1/g' -e 's/DENV2.*/NC_001474.2/g' -e 's/DENV3.*/NC_001475.2/g' -e 's/DENV4.*/NC_002640.1/g' -e 's/ZaireEbola.*/KR063671.1/g' -e 's/Lassa.*/NC_004296.1/g' -e 's/Nipah.*/AJ564622.1/g' -e 's/OROV400L/KP691612.1/g' -e 's/OROV400M/KP691622.1/g' -e 's/OROV400S/KP691623.1/g' -e 's/ARTIC.*/MN908947.3/g' -e 's/FIOCRUZ-IOC.*/MN908947.3/g' -e 's/MIDNIGHT.*/MN908947.3/g' -e 's/YFV.*/JF912190.1/g' -e 's/ZikaAsian.*/KJ776791.2/g' | sort -u)
                    mkdir "$ANALYSIS_DIR"/"$SAMPLE_ID"
                    fastp -i "$ANALYSIS_DIR"/"$SAMPLE_ID".R1.fastq.gz -I "$ANALYSIS_DIR"/"$SAMPLE_ID".R2.fastq.gz -o "$ANALYSIS_DIR"/"$SAMPLE_ID"/"$SAMPLE_ID".fastp.R1.fastq.gz -O "$ANALYSIS_DIR"/"$SAMPLE_ID"/"$SAMPLE_ID".fastp.R2.fastq.gz --cut_front --cut_tail --qualified_quality_phred 20 -l 75 -h "$ANALYSIS_DIR"/"$SAMPLE_ID"/"$SAMPLE_ID".fastp.html -j "$ANALYSIS_DIR"/"$SAMPLE_ID"/"$SAMPLE_ID".fastp.json --thread "$THREADS" --adapter_fasta $HOME/vigeas/illumina/primers/"$PRIMER_SCHEME".fasta -f 0 -t 0 -F 0 -T 0
                    bwa mem -t "$THREADS" $HOME/vigeas/illumina/refseqs_fasta/"$REF_SEQ".fasta "$ANALYSIS_DIR"/"$SAMPLE_ID"/"$SAMPLE_ID".fastp.R1.fastq.gz "$ANALYSIS_DIR"/"$SAMPLE_ID"/"$SAMPLE_ID".fastp.R2.fastq.gz -o "$ANALYSIS_DIR"/"$SAMPLE_ID"/"$SAMPLE_ID".bam
                    samtools sort -o "$ANALYSIS_DIR"/"$SAMPLE_ID"/"$SAMPLE_ID".sorted.bam "$ANALYSIS_DIR"/"$SAMPLE_ID"/"$SAMPLE_ID".bam
                    samtools index "$ANALYSIS_DIR"/"$SAMPLE_ID"/"$SAMPLE_ID".sorted.bam
                    samtools mpileup -d 50000 --reference $HOME/vigeas/illumina/refseqs_fasta/"$REF_SEQ".fasta -a -B "$ANALYSIS_DIR"/"$SAMPLE_ID"/"$SAMPLE_ID".sorted.bam | ivar variants -p "$ANALYSIS_DIR"/"$SAMPLE_ID"/"$SAMPLE_ID" -q 30 -t 0.05 -r $HOME/vigeas/illumina/refseqs_fasta/"$REF_SEQ".fasta -g $HOME/vigeas/illumina/refseqs_gff3/"$REF_SEQ".gff3
                    samtools mpileup -d 50000 --reference $HOME/vigeas/illumina/refseqs_fasta/"$REF_SEQ".fasta -a -B "$ANALYSIS_DIR"/"$SAMPLE_ID"/"$SAMPLE_ID".sorted.bam | ivar consensus -p "$ANALYSIS_DIR"/"$SAMPLE_ID"/"$SAMPLE_ID" -q 30 -t 0 -m "$DEPTH" -n N
                    sed -i -e 's/>.*/>'${SAMPLE_ID}'/g' "$ANALYSIS_DIR"/"$SAMPLE_ID"/"$SAMPLE_ID".fa
                    mafft --thread "$THREADS" --quiet --auto --keeplength --inputorder --6merpair --leavegappyregion --addfragments "$ANALYSIS_DIR"/"$SAMPLE_ID"/"$SAMPLE_ID".fa $HOME/vigeas/illumina/refseqs_fasta/"$REF_SEQ".fasta | seqkit grep -vip "$REF_SEQ" | sed '/>/!y/atcgn-/ATCGNN/' > "$ANALYSIS_DIR"/"$SAMPLE_ID"/"$SAMPLE_ID".depth"$DEPTH".fa
                    cat "$ANALYSIS_DIR"/"$SAMPLE_ID"/"$SAMPLE_ID".depth"$DEPTH".fa >> "$ANALYSIS_DIR"/"$LIBRARY_NAME".consensus."$REF_SEQ".$(uname -n).$(date +'%Y-%m-%d').fasta
                done
                conda deactivate
                if [[ ! -z $(cat "$SAMPLE_SHEET" | sed -e '1,18d' | awk -F, '{print $NF}' | sort -u | tr '\n' ',' | egrep "ARTIC|MIDNIGHT|FIOCRUZ-IOC") ]]; then
                    source activate vigeas_sars2
                    pangolin --update
                    [[ ! -d  $HOME/nextclade_db/sarscov2_$(date +'%Y-%m-%d') ]] && rm -rf $HOME/nextclade_db/sarscov2_* && mkdir -p $HOME/nextclade_db/sarscov2_$(date +'%Y-%m-%d') && nextclade dataset get --name 'sars-cov-2' --output-dir $HOME/nextclade_db/sarscov2_$(date +'%Y-%m-%d')
                    conda deactivate
                fi
                for i in $(cat "$SAMPLE_SHEET" | sed -e '1,18d' | awk -F, '{print $1","$NF}' | sort); do
                    SAMPLE_ID=$(echo "$i" | tr -dc '[:print:]\n' | awk -F, '{print $1}')
                    PRIMER_SCHEME=$(echo "$i" | tr -dc '[:print:]\n' | awk -F, '{print $2}')
                    if [[ ! -z $(echo "$PRIMER_SCHEME" | egrep "ARTIC|MIDNIGHT|FIOCRUZ-IOC") ]]; then
                        [[ ! -f "$ANALYSIS_DIR"/.summary_sars2.tmp ]] && echo "biobanco_seq#num_total_reads#num_mapp_reads#avg_depth#depth_10x#depth_100x#depth_1000x#ref_cov#ncount#ncount_perc#pango_ver#pango_learn_ver#pango_lin#nextclade_ver#clade#nucl_substitutions#nucl_deletions#nucl_inserc#nucl_missing#aa_substitutions#aa_deletions" | tr '#' '\t' > "$ANALYSIS_DIR"/.summary_sars2.tmp
                        source activate vigeas_summary
                        echo -n "#" | tr '#' '\n' >> "$ANALYSIS_DIR"/.summary_sars2.tmp
                        echo -n "$SAMPLE_ID""#" | tr '#' '\t' >> "$ANALYSIS_DIR"/.summary_sars2.tmp
                        samtools view -c "$ANALYSIS_DIR"/"$SAMPLE_ID"/"$SAMPLE_ID".sorted.bam | awk '{printf $0"#"}' | tr '#' '\t' >> "$ANALYSIS_DIR"/.summary_sars2.tmp
                        samtools view -c -h -F 4 "$ANALYSIS_DIR"/"$SAMPLE_ID"/"$SAMPLE_ID".sorted.bam | awk '{printf $0"#"}' | tr '#' '\t' >> "$ANALYSIS_DIR"/.summary_sars2.tmp
                        AVG_DEPTH=$(samtools depth "$ANALYSIS_DIR"/"$SAMPLE_ID"/"$SAMPLE_ID".sorted.bam | awk '{sum+=$3} END {print sum/NR}')
                        if [[ "$AVG_DEPTH" == 0 ]]; then
                            echo "0""#" | tr '#' '\t' | tr -d '\n' >> "$ANALYSIS_DIR"/.summary_sars2.tmp
                        else
                            echo "$AVG_DEPTH" | awk '{printf $0"#"}' | tr '#' '\t' | tr -d '\n' >> "$ANALYSIS_DIR"/.summary_sars2.tmp
                        fi
                        paste <(samtools depth "$ANALYSIS_DIR"/"$SAMPLE_ID"/"$SAMPLE_ID".sorted.bam | awk '{if ($3 > '"10"') {print $0}}' | wc -l) <(fastalength $HOME/vigeas/illumina/refseqs_fasta/"$REF_SEQ".fasta | awk '{print $1}') | awk -F"\t" '{printf("%0.2f\n", $1/$2*100)}' | awk '{printf $0"#"}' | tr '#' '\t' >> "$ANALYSIS_DIR"/.summary_sars2.tmp
                        paste <(samtools depth "$ANALYSIS_DIR"/"$SAMPLE_ID"/"$SAMPLE_ID".sorted.bam | awk '{if ($3 > '"100"') {print $0}}' | wc -l) <(fastalength $HOME/vigeas/illumina/refseqs_fasta/"$REF_SEQ".fasta | awk '{print $1}') | awk -F"\t" '{printf("%0.2f\n", $1/$2*100)}' | awk '{printf $0"#"}' | tr '#' '\t' >> "$ANALYSIS_DIR"/.summary_sars2.tmp
                        paste <(samtools depth "$ANALYSIS_DIR"/"$SAMPLE_ID"/"$SAMPLE_ID".sorted.bam | awk '{if ($3 > '"1000"') {print $0}}' | wc -l) <(fastalength $HOME/vigeas/illumina/refseqs_fasta/"$REF_SEQ".fasta | awk '{print $1}') | awk -F"\t" '{printf("%0.2f\n", $1/$2*100)}' | awk '{printf $0"#"}' | tr '#' '\t' >> "$ANALYSIS_DIR"/.summary_sars2.tmp
                        N_COUNT=$(seqtk comp "$ANALYSIS_DIR"/"$SAMPLE_ID"/"$SAMPLE_ID".depth"$DEPTH".fa | awk -F"\t" '{print $9}')
                        N_COUNT_PER=$(paste <(seqtk comp "$ANALYSIS_DIR"/"$SAMPLE_ID"/"$SAMPLE_ID".depth"$DEPTH".fa | awk -F"\t" '{print $9}') <(fastalength $HOME/vigeas/illumina/refseqs_fasta/"$REF_SEQ".fasta | awk '{print $1}')| awk -F"\t" '{printf("%0.2f\n", ($1/$2)*100)}')
                        REF_SEQ_LENGHT=$(fastalength $HOME/vigeas/illumina/refseqs_fasta/"$REF_SEQ".fasta | awk -F" " '{print $1}')
                        REF_SEQ_COV=$(paste <(fastalength $HOME/vigeas/illumina/refseqs_fasta/"$REF_SEQ".fasta | awk '{print $1}') <(seqtk comp "$ANALYSIS_DIR"/"$SAMPLE_ID"/"$SAMPLE_ID".depth"$DEPTH".fa | awk -F"\t" '{print $9}') | awk -F"\t" '{printf("%0.2f\n", ($1-$2)/$1*100)}')
                        conda deactivate
                        if [[ "$N_COUNT" == 0 ]]; then
                            echo "0" | awk '{printf $0"#"}' | tr '#' '\t' | tr -d '\n' >> "$ANALYSIS_DIR"/.summary_sars2.tmp
                            echo "$REF_SEQ_LENGHT" | awk '{printf $0"#"}' | tr '#' '\t' | tr -d '\n' >> "$ANALYSIS_DIR"/.summary_sars2.tmp
                            echo "100" | awk '{printf $0"#"}' | tr '#' '\t' | tr -d '\n' >> "$ANALYSIS_DIR"/.summary_sars2.tmp
                        else
                            echo "$REF_SEQ_COV" | awk '{printf $0"#"}' | tr '#' '\t' | tr -d '\n' >> "$ANALYSIS_DIR"/.summary_sars2.tmp
                            echo "$N_COUNT" | awk '{printf $0"#"}' | tr '#' '\t' | tr -d '\n' >> "$ANALYSIS_DIR"/.summary_sars2.tmp
                            echo "$N_COUNT_PER" | awk '{printf $0"#"}' | tr '#' '\t' | tr -d '\n' >> "$ANALYSIS_DIR"/.summary_sars2.tmp
                        fi
                        source activate vigeas_sars2
                        pangolin "$ANALYSIS_DIR"/"$SAMPLE_ID"/"$SAMPLE_ID".depth"$DEPTH".fa -t "$THREADS" --outfile "$ANALYSIS_DIR"/"$SAMPLE_ID"/"$SAMPLE_ID".pangolin.csv
                        cat "$ANALYSIS_DIR"/"$SAMPLE_ID"/"$SAMPLE_ID".pangolin.csv | sed -n 2p | awk -F, '{print $10"\t"$9"\t"$2}' | awk '{printf $0"#"}' | tr '#' '\t' >> "$ANALYSIS_DIR"/.summary_sars2.tmp
                        nextclade run --input-dataset $HOME/nextclade_db/sarscov2_$(date +'%Y-%m-%d') --output-tsv="$ANALYSIS_DIR"/"$SAMPLE_ID"/"$SAMPLE_ID".nextclade.tsv "$ANALYSIS_DIR"/"$SAMPLE_ID"/"$SAMPLE_ID".depth"$DEPTH".fa
                        nextclade --version | awk '{print $2}' | awk '{printf $0"#"}' | tr '#' '\t' >> "$ANALYSIS_DIR"/.summary_sars2.tmp
                        cat "$ANALYSIS_DIR"/"$SAMPLE_ID"/"$SAMPLE_ID".nextclade.tsv | sed -n 2p | awk -F"\t" '{print $2"\t"$16"\t"$17"\t"$18"\t"$30"\t"$27"\t"$28}' | awk '{printf $0}' >> "$ANALYSIS_DIR"/.summary_sars2.tmp
                        conda deactivate
                        source activate vigeas_summary
                        fastcov.py -l "$ANALYSIS_DIR"/"$SAMPLE_ID"/"$SAMPLE_ID".sorted.bam -o "$ANALYSIS_DIR"/"$SAMPLE_ID"/"$SAMPLE_ID".coverage.pdf
                        sed '/^[[:space:]]*$/d' "$ANALYSIS_DIR"/.summary_sars2.tmp > "$ANALYSIS_DIR"/"$LIBRARY_NAME".summary.MN908947.3.$(uname -n).$(date +'%Y-%m-%d').txt
                    else
                        [[ ! -f "$ANALYSIS_DIR"/.summary.tmp ]] && echo "biobanco_seq#num_total_reads#num_mapp_reads#avg_depth#depth_10x#depth_100x#depth_1000x#ref_cov#ncount#ncount_perc" | tr '#' '\t' > "$ANALYSIS_DIR"/.summary.tmp
                        source activate vigeas_summary
                        echo -n "#" | tr '#' '\n' >> "$ANALYSIS_DIR"/.summary.tmp
                        echo -n "$SAMPLE_ID""#" | tr '#' '\t' >> "$ANALYSIS_DIR"/.summary.tmp
                        samtools view -c "$ANALYSIS_DIR"/"$SAMPLE_ID"/"$SAMPLE_ID".sorted.bam | awk '{printf $0"#"}' | tr '#' '\t' >> "$ANALYSIS_DIR"/.summary.tmp
                        samtools view -c -h -F 4 "$ANALYSIS_DIR"/"$SAMPLE_ID"/"$SAMPLE_ID".sorted.bam | awk '{printf $0"#"}' | tr '#' '\t' >> "$ANALYSIS_DIR"/.summary.tmp
                        AVG_DEPTH=$(samtools depth "$ANALYSIS_DIR"/"$SAMPLE_ID"/"$SAMPLE_ID".sorted.bam | awk '{sum+=$3} END {print sum/NR}')
                        if [[ "$AVG_DEPTH" == 0 ]]; then
                            echo "0""#" | tr '#' '\t' | tr -d '\n' >> "$ANALYSIS_DIR"/.summary.tmp
                        else
                            echo "$AVG_DEPTH" | awk '{printf $0"#"}' | tr '#' '\t' | tr -d '\n' >> "$ANALYSIS_DIR"/.summary.tmp
                        fi
                        paste <(samtools depth "$ANALYSIS_DIR"/"$SAMPLE_ID"/"$SAMPLE_ID".sorted.bam | awk '{if ($3 > '"10"') {print $0}}' | wc -l) <(fastalength $HOME/vigeas/illumina/refseqs_fasta/"$REF_SEQ".fasta | awk '{print $1}') | awk -F"\t" '{printf("%0.2f\n", $1/$2*100)}' | awk '{printf $0"#"}' | tr '#' '\t' >> "$ANALYSIS_DIR"/.summary.tmp
                        paste <(samtools depth "$ANALYSIS_DIR"/"$SAMPLE_ID"/"$SAMPLE_ID".sorted.bam | awk '{if ($3 > '"100"') {print $0}}' | wc -l) <(fastalength $HOME/vigeas/illumina/refseqs_fasta/"$REF_SEQ".fasta | awk '{print $1}') | awk -F"\t" '{printf("%0.2f\n", $1/$2*100)}' | awk '{printf $0"#"}' | tr '#' '\t' >> "$ANALYSIS_DIR"/.summary.tmp
                        paste <(samtools depth "$ANALYSIS_DIR"/"$SAMPLE_ID"/"$SAMPLE_ID".sorted.bam | awk '{if ($3 > '"1000"') {print $0}}' | wc -l) <(fastalength $HOME/vigeas/illumina/refseqs_fasta/"$REF_SEQ".fasta | awk '{print $1}') | awk -F"\t" '{printf("%0.2f\n", $1/$2*100)}' | awk '{printf $0"#"}' | tr '#' '\t' >> "$ANALYSIS_DIR"/.summary.tmp
                        N_COUNT=$(seqtk comp "$ANALYSIS_DIR"/"$SAMPLE_ID"/"$SAMPLE_ID".depth"$DEPTH".fa | awk -F"\t" '{print $9}')
                        N_COUNT_PER=$(paste <(seqtk comp "$ANALYSIS_DIR"/"$SAMPLE_ID"/"$SAMPLE_ID".depth"$DEPTH".fa | awk -F"\t" '{print $9}') <(fastalength $HOME/vigeas/illumina/refseqs_fasta/"$REF_SEQ".fasta | awk '{print $1}')| awk -F"\t" '{printf("%0.2f\n", ($1/$2)*100)}')
                        REF_SEQ_LENGHT=$(fastalength $HOME/vigeas/illumina/refseqs_fasta/"$REF_SEQ".fasta | awk -F" " '{print $1}')
                        REF_SEQ_COV=$(paste <(fastalength $HOME/vigeas/illumina/refseqs_fasta/"$REF_SEQ".fasta | awk '{print $1}') <(seqtk comp "$ANALYSIS_DIR"/"$SAMPLE_ID"/"$SAMPLE_ID".depth"$DEPTH".fa | awk -F"\t" '{print $9}') | awk -F"\t" '{printf("%0.2f\n", ($1-$2)/$1*100)}')
                        if [[ "$N_COUNT" == 0 ]]; then
                            echo "0" | awk '{printf $0"#"}' | tr '#' '\t' | tr -d '\n' >> "$ANALYSIS_DIR"/.summary.tmp
                            echo "$REF_SEQ_LENGHT" | awk '{printf $0"#"}' | tr '#' '\t' | tr -d '\n' >> "$ANALYSIS_DIR"/.summary.tmp
                            echo "100" | awk '{printf $0"#"}' | tr '#' '\t' | tr -d '\n' >> "$ANALYSIS_DIR"/.summary.tmp
                        else
                            echo "$REF_SEQ_COV" | awk '{printf $0"#"}' | tr '#' '\t' | tr -d '\n' >> "$ANALYSIS_DIR"/.summary.tmp
                            echo "$N_COUNT" | awk '{printf $0"#"}' | tr '#' '\t' | tr -d '\n' >> "$ANALYSIS_DIR"/.summary.tmp
                            echo "$N_COUNT_PER" | awk '{printf $0}' >> "$ANALYSIS_DIR"/.summary.tmp
                        fi
                        fastcov.py -l "$ANALYSIS_DIR"/"$SAMPLE_ID"/"$SAMPLE_ID".sorted.bam -o "$ANALYSIS_DIR"/"$SAMPLE_ID"/"$SAMPLE_ID".coverage.pdf
                        sed '/^[[:space:]]*$/d' "$ANALYSIS_DIR"/.summary.tmp > "$ANALYSIS_DIR"/"$LIBRARY_NAME".summary.$(uname -n).$(date +'%Y-%m-%d').txt
                    fi
                done
                gs -dSAFER -r3000 -sDEVICE=pdfwrite -dNOPAUSE -dBATCH -sOUTPUTFILE="$ANALYSIS_DIR"/"$LIBRARY_NAME".coverage.$(uname -n).$(date +'%Y-%m-%d').pdf "$ANALYSIS_DIR"/*/*.pdf
                conda deactivate
            fi
        elif [[ "$WORKFLOW" == "2" ]]; then
            if [[ -z "$INPUT" ]] || [[ -z "$SAMPLE_SHEET" ]] || [[ -z "$DEPTH" ]]; then
                usage
            else
                for i in $(cat "$SAMPLE_SHEET" | sed -e '1,18d' | awk -F, '{print $1}' | sort); do
                    if [[ $(find "$INPUT" -type f -name '*_L00*') ]]; then
                        cp -v "$INPUT"/"$i"*_R1_001.fastq.gz "$ANALYSIS_DIR"/"$i".R1.fastq.gz
                        cp -v "$INPUT"/"$i"*_R2_001.fastq.gz "$ANALYSIS_DIR"/"$i".R2.fastq.gz
                    elif [[ $(find "$INPUT" -type f -name '*_1.fastq.gz') ]]; then
                        cp -v "$INPUT"/"$i"_1.fastq.gz "$ANALYSIS_DIR"/"$i".R1.fastq.gz
                        cp -v "$INPUT"/"$i"_2.fastq.gz "$ANALYSIS_DIR"/"$i".R2.fastq.gz
                    elif [[ $(find "$INPUT" -type f -name '*.R[1-2].fastq.gz') ]]; then
                        cp -v "$INPUT"/"$i".R1.fastq.gz "$ANALYSIS_DIR"/"$i".R1.fastq.gz
                        cp -v "$INPUT"/"$i".R2.fastq.gz "$ANALYSIS_DIR"/"$i".R2.fastq.gz
                    fi
                done
                source activate vigeas_illumina
                for i in $(cat "$SAMPLE_SHEET" | sed -e '1,18d' | awk -F, '{print $NF}' | sed -e 's/ChikAsianECSA.*/KP164568.1/g' -e 's/DENV1.*/NC_001477.1/g' -e 's/DENV2.*/NC_001474.2/g' -e 's/DENV3.*/NC_001475.2/g' -e 's/DENV4.*/NC_002640.1/g' -e 's/ZaireEbola.*/KR063671.1/g' -e 's/Lassa.*/NC_004296.1/g' -e 's/Nipah.*/AJ564622.1/g' -e 's/OROV400L/KP691612.1/g' -e 's/OROV400M/KP691622.1/g' -e 's/OROV400S/KP691623.1/g' -e 's/ARTIC.*/MN908947.3/g' -e 's/FIOCRUZ-IOC.*/MN908947.3/g' -e 's/MIDNIGHT.*/MN908947.3/g' -e 's/YFV.*/JF912190.1/g' -e 's/ZikaAsian.*/KJ776791.2/g' | sort -u); do
                    bwa index $HOME/vigeas/illumina/refseqs_fasta/"$i".fasta
                done
                for i in $(cat "$SAMPLE_SHEET" | sed -e '1,18d' | awk -F, '{print $1","$NF}' | sort); do
                    SAMPLE_ID=$(echo "$i" | tr -dc '[:print:]\n' | awk -F, '{print $1}')
                    PRIMER_SCHEME=$(echo "$i" | tr -dc '[:print:]\n' | awk -F, '{print $2}')
                    REF_SEQ=$(echo "$PRIMER_SCHEME" | sed -e 's/ChikAsianECSA.*/KP164568.1/g' -e 's/DENV1.*/NC_001477.1/g' -e 's/DENV2.*/NC_001474.2/g' -e 's/DENV3.*/NC_001475.2/g' -e 's/DENV4.*/NC_002640.1/g' -e 's/ZaireEbola.*/KR063671.1/g' -e 's/Lassa.*/NC_004296.1/g' -e 's/Nipah.*/AJ564622.1/g' -e 's/OROV400L/KP691612.1/g' -e 's/OROV400M/KP691622.1/g' -e 's/OROV400S/KP691623.1/g' -e 's/ARTIC.*/MN908947.3/g' -e 's/FIOCRUZ-IOC.*/MN908947.3/g' -e 's/MIDNIGHT.*/MN908947.3/g' -e 's/YFV.*/JF912190.1/g' -e 's/ZikaAsian.*/KJ776791.2/g' | sort -u)
                    mkdir "$ANALYSIS_DIR"/"$SAMPLE_ID"
                    fastp -i "$ANALYSIS_DIR"/"$SAMPLE_ID".R1.fastq.gz -I "$ANALYSIS_DIR"/"$SAMPLE_ID".R2.fastq.gz -o "$ANALYSIS_DIR"/"$SAMPLE_ID"/"$SAMPLE_ID".fastp.R1.fastq.gz -O "$ANALYSIS_DIR"/"$SAMPLE_ID"/"$SAMPLE_ID".fastp.R2.fastq.gz --cut_front --cut_tail --qualified_quality_phred 20 -l 75 -h "$ANALYSIS_DIR"/"$SAMPLE_ID"/"$SAMPLE_ID".fastp.html -j "$ANALYSIS_DIR"/"$SAMPLE_ID"/"$SAMPLE_ID".fastp.json --thread "$THREADS" --adapter_fasta $HOME/vigeas/illumina/primers/"$PRIMER_SCHEME".fasta -f 0 -t 0 -F 0 -T 0
                    bwa mem -t "$THREADS" $HOME/vigeas/illumina/refseqs_fasta/"$REF_SEQ".fasta "$ANALYSIS_DIR"/"$SAMPLE_ID"/"$SAMPLE_ID".fastp.R1.fastq.gz "$ANALYSIS_DIR"/"$SAMPLE_ID"/"$SAMPLE_ID".fastp.R2.fastq.gz -o "$ANALYSIS_DIR"/"$SAMPLE_ID"/"$SAMPLE_ID".bam
                    samtools sort -o "$ANALYSIS_DIR"/"$SAMPLE_ID"/"$SAMPLE_ID".sorted.bam "$ANALYSIS_DIR"/"$SAMPLE_ID"/"$SAMPLE_ID".bam
                    samtools index "$ANALYSIS_DIR"/"$SAMPLE_ID"/"$SAMPLE_ID".sorted.bam
                    samtools mpileup -d 50000 --reference $HOME/vigeas/illumina/refseqs_fasta/"$REF_SEQ".fasta -a -B "$ANALYSIS_DIR"/"$SAMPLE_ID"/"$SAMPLE_ID".sorted.bam | ivar variants -p "$ANALYSIS_DIR"/"$SAMPLE_ID"/"$SAMPLE_ID" -q 30 -t 0.05 -r $HOME/vigeas/illumina/refseqs_fasta/"$REF_SEQ".fasta -g $HOME/vigeas/illumina/refseqs_gff3/"$REF_SEQ".gff3
                    samtools mpileup -d 50000 --reference $HOME/vigeas/illumina/refseqs_fasta/"$REF_SEQ".fasta -a -B "$ANALYSIS_DIR"/"$SAMPLE_ID"/"$SAMPLE_ID".sorted.bam | ivar consensus -p "$ANALYSIS_DIR"/"$SAMPLE_ID"/"$SAMPLE_ID" -q 30 -t 0 -m "$DEPTH" -n N
                    sed -i -e 's/>.*/>'${SAMPLE_ID}'/g' "$ANALYSIS_DIR"/"$SAMPLE_ID"/"$SAMPLE_ID".fa
                    mafft --thread "$THREADS" --quiet --auto --keeplength --inputorder --6merpair --leavegappyregion --addfragments "$ANALYSIS_DIR"/"$SAMPLE_ID"/"$SAMPLE_ID".fa $HOME/vigeas/illumina/refseqs_fasta/"$REF_SEQ".fasta | seqkit grep -vip "$REF_SEQ" | sed '/>/!y/atcgn-/ATCGNN/' > "$ANALYSIS_DIR"/"$SAMPLE_ID"/"$SAMPLE_ID".depth"$DEPTH".fa
                    cat "$ANALYSIS_DIR"/"$SAMPLE_ID"/"$SAMPLE_ID".depth"$DEPTH".fa >> "$ANALYSIS_DIR"/"$LIBRARY_NAME".consensus."$REF_SEQ".$(uname -n).$(date +'%Y-%m-%d').fasta
                done
                conda deactivate
            fi
        else
            usage
        fi
    else
        usage
    fi

    # rm -rf "$ANALYSIS_DIR"/*.fastq.gz "$ANALYSIS_DIR"/*.tmp $HOME/vigeas/illumina/refseqs/*.fasta.amb $HOME/vigeas/illumina/refseqs/*.fasta.ann $HOME/vigeas/illumina/refseqs/*.fasta.bwt $HOME/vigeas/illumina/refseqs/*.fasta.fai $HOME/vigeas/illumina/refseqs/*.fasta.pac $HOME/vigeas/illumina/refseqs/*.fasta.sa

    end_all=$(date +%s.%N)

    runtime_all=$(python -c "print(${end_all} - ${start_all})")

    echo "" && echo "Done. The runtime was "$runtime_all" seconds." && echo ""

}

bg &>>"$ANALYSIS_DIR"/"$LIBRARY_NAME".log.$(uname -n).$(date +'%Y-%m-%d').txt &

exit 0
